language: go
go:
  - "1.11"

branches:
  only:
    - master

before_script:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

script:
  - make compile

after_success:
  - if [ $(git tag -l "$(cat VERSION)") ]; then echo "Version already exists" && false; fi

before_deploy:
  - git config --local user.name "TravisCI"
  - git config --local user.email "TravisCI"
  - git tag "$(cat VERSION)"

deploy:
  provider: releases
  api_key:
    secure: hDEakaIFo+J/R66MUqY8LoXmu2k0AHp1/KZXQtb0M7jJBA+89z7I/xUFr7qKZ0Zo2whv0LPRxmhHuI5T3S28BMHbT5/arq2wLqubjMO29xhpmCuZiFMA/JyI6t1lRIhlijc1Yt81sJeC/2kPYGnayR+NmDRNgyZ4aTANfi+xh8cOUFrR1NMnInRKus7+QqUzNZetuH+xMMSq9oRt42ooSN8+PyWOMR48eAiomKkAqE0683HWw1f9FfhxM9o+t/n0ARqkRSBHRGg7hy6L1PFK23mq65a2VaB5qwI63899YcZ1m8jOoX+PVT6oAzDKNSEH8SDe+Mc9QaLmqgkcwfTrqZKrsNkrpLGTB1Jzf9GvfKBSlRnI1geLEJeV9pqZDy0i7Lb1sa5X7Vl4cYzJTvVfRwGVntj37v1FthY5YEOkaCYd1jVLHMUsIuZ1rZsiyjtL5gO12jvxUb0vkY75njERiY+xgV+QBp8wwAcYnMcTYEOsKF7hBjnWrLjSDpSU7pv/FdGTZaZlgoKj8ibbNo2YShHdPdXvWqJh/FRj9eTtyhxyuxrF9CX0ne0356Ptc+v3dl1Q7zMnwXjWgCPN9nCMLRSlfWxAAL96zRLfm5It8+MwIYm32L2rFW77OdDI3t4Ebt1meGwOJAQSvJMfDuH7Okot95u1d+2dCqOWhHRN2Lg=
  file: bin/loro
  skip_cleanup: true
  on:
    repo: pecigonzalo/loro

env:
  - DEP_VERSION="0.5.0"
